format = """
[](#7F3FBF)\
$username\
[](bg:#7F7FFF fg:#7F3FBF)\
$directory\
[](fg:#7F7FFF bg:#FF7F7F)\
$git_branch\
$git_status\
[](fg:#FF7F7F bg:#BE9EDE)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#BE9EDE bg:#BEBEFF)\
$docker_context\
[](fg:#BEBEFF bg:#7F3FBF)\
$time\
[ ](fg:#7F3FBF)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#7F3FBF"
style_root = "bg:#7F3FBF"
format = '[$user ]($style)'

[directory]
style = "bg:#7F7FFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#BE9EDE"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#BEBEFF"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#BE9EDE"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#BE9EDE"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FF7F7F"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FF7F7F"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#BE9EDE"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#BE9EDE"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#BE9EDE"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#BE9EDE"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#BE9EDE"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#BE9EDE"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#BE9EDE"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#7F3FBF"
format = '[ $time ]($style)'
